[tool.poetry]
name = "noccrootstock"
version = "0.1.0"
description = "noccrootstock using crewAI"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
crewai = { extras = ["tools"], version = ">=0.63.6,<1.0.0" }


[tool.poetry.scripts]
noccrootstock = "noccrootstock.main:run"
run_crew = "noccrootstock.main:run"
train = "noccrootstock.main:train"
replay = "noccrootstock.main:replay"
test = "noccrootstock.main:test"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
